import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import { ConfigProvider } from 'antd'
import locale from 'antd/locale/id_ID'
import CreatePostContextProvider from '@/contexts/CreatePostContext'
import UserContextProvider from '@/contexts/UserContext'
import AuthContextProvider from '@/contexts/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white`}>
        <NextTopLoader
          color="#a8a8a8"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #a8a8a8,0 0 5px #a8a8a8"
          template={`<div class="bar" role="bar"><div class="peg"></div></div> 
          <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>`}
          zIndex={1600}
          showAtBottom={false}
        />
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorText: 'white',
              colorPrimary: '#a8a8a8',
              borderRadius: 5,
            },
          }}
          locale={locale}
        >
          <UserContextProvider>
            <AuthContextProvider>
              <CreatePostContextProvider>{children}</CreatePostContextProvider>
            </AuthContextProvider>
          </UserContextProvider>
        </ConfigProvider>
      </body>
    </html>
  )
}
